### ISSUE TITLE
What a dickhead. 

### ISSUE THREAD

**Issue by crabcrabcamTest** [crabcrabcam/0ATestRepo#58]
He really is, isn't he!

**Comment by crabcrabcam** [comment]
Fuk off m8

**Comment by crabcrabcam** [comment]
[This is a link](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by crabcrabcam** [comment]
![10 steve-irwin_2](https://cloud.githubusercontent.com/assets/13933264/25898917/d52d1698-3585-11e7-8b5a-ea5a7b30ed40.jpg)
[This is a link](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
